# Over here we need  the 01_d csv file 

 then using the  01_d,  12_c  csv file is created.

In [ ]:
from datetime import datetime
import uuid
import random
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/KislayKaran/Walmart_Supermarket/main/Required_CSV_files/01_d_walmart_stores_2018_11_06_(downloaded_csv).csv')
df.head()

,name,url,street_address,city,state,zip_code,country,phone_number_1,phone_number_2,fax_1,...,email_2,website,open_hours,latitude,longitude,facebook,twitter,instagram,pinterest,youtube
0,Conway Supercenter,https://www.walmart.com/store/5/conway-ar/details,1155 Hwy 65 North,Conway,AR,72032,US,501-329-0023,NaN,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",35.108660,-92.436905,NaN,NaN,NaN,NaN,NaN
1,Sikeston Supercenter,https://www.walmart.com/store/9/sikeston-mo/de...,1303 S Main St,Sikeston,MO,63801,US,573-472-3020,NaN,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",36.857394,-89.586051,NaN,NaN,NaN,NaN,NaN
2,Tahlequah Supercenter,https://www.walmart.com/store/10/tahlequah-ok/...,2020 S Muskogee Ave,Tahlequah,OK,74464,US,918-456-8804,NaN,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",35.888765,-94.979859,NaN,NaN,NaN,NaN,NaN
3,Mountain Home Supercenter,https://www.walmart.com/store/11/mountain-home...,65 Wal Mart Dr,Mountain Home,AR,72653,US,870-492-9299,NaN,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",36.354957,-92.341026,NaN,NaN,NaN,NaN,NaN
4,Claremore Supercenter,https://www.walmart.com/store/12/claremore-ok/...,1500 S Lynn Riggs Blvd,Claremore,OK,74017,US,918-341-2765,NaN,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",36.293955,-95.627125,NaN,NaN,NaN,NaN,NaN

Adding the Custom ID to the each Walmart Store (UUID) along with the selected Fields

In [ ]:
df=df[['name','street_address','city','state','latitude','longitude']]
df.head()

,name,street_address,city,state,latitude,longitude
0,Conway Supercenter,1155 Hwy 65 North,Conway,AR,35.108660,-92.436905
1,Sikeston Supercenter,1303 S Main St,Sikeston,MO,36.857394,-89.586051
2,Tahlequah Supercenter,2020 S Muskogee Ave,Tahlequah,OK,35.888765,-94.979859
3,Mountain Home Supercenter,65 Wal Mart Dr,Mountain Home,AR,36.354957,-92.341026
4,Claremore Supercenter,1500 S Lynn Riggs Blvd,Claremore,OK,36.293955,-95.627125

In [ ]:
df['store_id'] = df.apply(lambda _: uuid.uuid4(), axis=1)

In [ ]:
df.head()

,name,street_address,city,state,latitude,longitude,store_id
0,Conway Supercenter,1155 Hwy 65 North,Conway,AR,35.108660,-92.436905,8f9760a1-0021-4fc7-98d2-af8d6f1d37a3
1,Sikeston Supercenter,1303 S Main St,Sikeston,MO,36.857394,-89.586051,d1bc7fac-c364-4793-94da-a2b10ecd620f
2,Tahlequah Supercenter,2020 S Muskogee Ave,Tahlequah,OK,35.888765,-94.979859,8b51082a-5f94-4e98-9994-6f32e7836de6
3,Mountain Home Supercenter,65 Wal Mart Dr,Mountain Home,AR,36.354957,-92.341026,1023f155-5c97-42c2-9b9a-d2ccec83fff0
4,Claremore Supercenter,1500 S Lynn Riggs Blvd,Claremore,OK,36.293955,-95.627125,8b03ccb8-b285-4f0b-8fe1-0fa130682c15

In [ ]:
df.to_csv('12_c_master_store_data_(created_csv).csv')

In [ ]:
!ls -lash /content

total 552K
4.0K drwxr-xr-x 1 root root 4.0K Aug  9 15:19  .
4.0K drwxr-xr-x 1 root root 4.0K Aug  9 14:59  ..
536K -rw-r--r-- 1 root root 533K Aug  9 15:19 '12_c_master_store_data_(created_csv).csv'
4.0K drwxr-xr-x 4 root root 4.0K Aug  3 20:20  .config
4.0K drwxr-xr-x 1 root root 4.0K Aug  3 20:21  sample_data